export const BUSINESS_INFO = {
  brandName: "Windows Plaza",
  parentCompany: "SP Builders and Traders",
  tagline: "Direct uPVC Windows Manufacturer in Visakhapatnam",
  description:
    "Direct uPVC windows manufacturer and installer in Visakhapatnam. Custom sizes, free site measurement, and professional installation. GST Registered Company.",
  gstNote: "GST Registered",
  email: "info@windowsplaza.in",
  phoneNumber: "+91-8341166268",
  phoneHref: "tel:+918341166268",
  phoneRaw: "918341166268",
  location: {
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    country: "India",
    display: "Visakhapatnam, Andhra Pradesh, India",
    full: "Rajula Tallavalasa, Near Thirumala College, Bheemunipatnam, Visakhapatnam, Andhra Pradesh – 531162",
    postalCode: "531162",
    streetAddress: "Rajula Tallavalasa, Near Thirumala College, Bheemunipatnam",
  },
  serviceAreas: [
    "Visakhapatnam (Vizag)",
    "Bheemili",
    "Madhurawada",
    "Anandapuram",
    "Rushikonda",
    "MVP Colony",
    "Gajuwaka",
    "Pendurthi",
    "Bheemunipatnam",
    "Seethammadhara",
    "Dwaraka Nagar",
    "Waltair",
  ],
  buildingTypes: ["Apartment", "Villa", "Commercial", "Independent House"],
  workingHours: "Mon–Sat, 9 AM – 6 PM",
} as const
